### PR TITLE
[Proposal] - Minimize changes

### PR DESCRIPTION
**Pull request by gave92**
@AndyMDoyle Sorry this PR came out wrong as I merged master in the meantime 🤦‍♂️ (also PR made to the wrong branch 🤦‍♂️🤦‍♂️)
Anyway if you only look at the relevant files, this PR would reduce the changes to implement #3095
- Keep an AppServiceConnection for each tab. I'm positive there was a reason for which we moved from a single global Connection to the current model, such change would have more impact that I'd like
- Remove the marco-polo. Instead of checking if the fulltrust process is connected I'm just retrying the same request until it succeeds (or a timeout expires)
- Keep the existing code for Drive enumeration, fixed drives are shown immediatly, virtual drives are added when all providers are done

What do you think?

### CODE REVIEW

**Comment by AndyMDoyle** [comment]
@gave92, this looks a lot cleaner and simpler and shouldn't require changes to too many files.
How would you like to move this forward? Do you want to merge this in from your branch or would you like me to implement these changes (excluding the unrelated other changes) and update my PR?

**Comment by gave92** [comment]
If you are ok with the proposed changes perhaps you can merge this PR to your branch. Were you planning to address #3151 as well?

**Comment by AndyMDoyle** [comment]
@gave92, there is lots of other work in this PR that is unrelated to OneDrive so merging this in might complicate things. I have tried to pick the key changes but it is resulting in a lot of messy history.

I am doing to start a new branch based on master and do these initial OneDrive changes and raise a new PR quickly so it can be reviewed and merged. Once that is done I can pick up https://github.com/files-community/Files/issues/3151 no problem.

**Comment by gave92** [comment]
@AndyMDoyle thanks that works too. (The changes were the result of merging master so just merging the PR should have worked too, sorry for the confusion)

**Comment by AndyMDoyle** [comment]
@gave92 , PR https://github.com/files-community/Files/pull/3177 is ready and waiting.
Hope I haven't missed anything.

Thanks for the help!

**Pull request closed without merging**
